# Generated by Django 4.2.2 on 2023-06-22 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_notes', '0002_rename_personalnotes_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='user',
            field=models.ManyToManyField(related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
