# Generated by Django 4.2.2 on 2023-06-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_notes', '0003_personalnote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='user',
        ),
    ]
